project:
  type: website
  
website:
  title: "Visual Analytics for Singapore's Weather"
  navbar:
    left:
    - text: "Proposal"
      href: "Project/Project_Proposal/Project_Proposal.html"
        
    - text: "Meeting Minutes"
      menu:
      - text: "Meeting Minutes 1"
        href: "Project/Meeting_Minutes/Meeting_Minutes1.html"
        
      - text: "Meeting Minutes 2"
        href: "Project/Meeting_Minutes/Meeting_Minutes2.html"
      
    - text: "Project Code"
      href: "Project/Project_Code/Project_Code.html"
      
    - text: "User Guide"
      menu: 
      - text: "Forecasting User Guide"
        href: "Project/UserGuide/UserGuide.html"
      menu:
      - text: "Geospatial User Guide"
        href: "Project/User_Geospatial/User_Geospatial.html"
        
    - text: "Shiny App"
      href: https://brigittatsai.shinyapps.io/ISSS608_Group1/

    right: 
      - href: index.qmd
        text: Home
      - about.qmd
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
editor: visual