project:
  type: website
  
website:
  title: "Visual Analytics Project - Group 1"
  navbar:
    left:
    - text: "Project Proposal"
      href: "Project/Project_Proposal/Project_Proposal.html"


    right: 
      - href: index.qmd
        text: Home
      - about.qmd
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
editor: visual