project:
  type: website
  
website:
  title: "Visual Analytics for Singapore's Weather"
  sidebar:
    style: "docked" 
    contents:
      - href: "Project/Project_Proposal/Project_Proposal.html"
        text: "Home"
        
      - href: https://brigittatsai.shinyapps.io/ISSS608_Group1/
        text: "Shiny App"
        
      - href: "Project/Meeting_Minutes/Meeting_Minutes1.html"
        text: "Meeting Minutes"
      
      - href: "Project/Project_Code/Project_Code.html"
        text: "Project Code"
        


    right: 
      - href: index.qmd
        text: Home
      - about.qmd
format:
  html:
    include-after-body: _footer.html
    theme: flatly
    css: styles.css
    toc: true
    
editor: visual