project:
  type: website
  
website:
  title: "Singapore Weather Demystified: Visualizing Atmospheric Data"
  navbar:
    left:
    - text: "Main Page"
      href: "Project/Project_Proposal/Project_Proposal.html"
        
    - text: "Meeting Minutes"
      menu:
      - text: "Meeting Minutes 1"
        href: "Project/Meeting_Minutes/Meeting_Minutes1.html"
        
      - text: "Meeting Minutes 2"
        href: "Project/Meeting_Minutes/Meeting_Minutes2.html"
        
      - text: "Meeting Minutes 3"
        href: "Project/Meeting_Minutes/Meeting_Minutes3.html"
      
    - text: "Project Code"
      href: "Project/Project_Code/Project_Code.html"
      
    - text: "User Guide"
      menu: 
      - text: "Forecasting User Guide"
        href: "Project/UserGuide/User_Forecasting.html"
      - text: "Geospatial User Guide"
        href: "Project/UserGuide/User_Geospatial.html"
      - text: "Time Series & EDA User Guide"
        href: "Project/UserGuide/User_EDA.html"
        
    - text: "Shiny App"
      href: https://brigittatsai.shinyapps.io/ISSS608_Group1/

    right: 
      - href: index.qmd
        text: Home
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
editor: visual