project:
  type: website

website:
  title: "ISSS608_AY2024-25_T2_Group1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

