---
title: "Group_Project"
author: "Brigitta Karen Tsai"
date: "March 10, 2025"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  message: false
  freeze: true
---

## 1 Weather Data (Trial)

```{r}
pacman::p_load(sp, sf, raster, spatstat, tmap, tidyverse,
               spNetwork, tmaptools)
```

```{r}
c124 <- read_csv("data/changi_124.csv")
```

```{r}
geo = st_read(dsn = "data/geospatial", 
                  layer = "MP14_SUBZONE_WEB_PL")
```

```{r}
st_geometry(geo)
```

```{r}
plot(st_geometry(geo))
```

```{r}
st_crs(geo)
```

```{r}
geo <- st_transform(geo, 3414)
```

```{r}
changi <- geo %>%
  filter(SUBZONE_N %in% c("CHANGI AIRPORT", "CHANGI BAY",
                          "CHANGI POINT", "CHANGI WEST"))
```

```{r}
changi <- changi %>% 
  mutate(Station = "Changi")
```

```{r}
changi <- changi %>%
  relocate(Station, .before = everything())
```

```{r}
changi <- left_join(changi, c124,
                    by = c("Station" = "Station"))
```

```{r}
ggplot(changi) +
  geom_sf(aes(fill = `Mean Temperature (°C)`), color = "black") + 
  scale_fill_gradient(low = "blue", high = "red", name = "Mean Temp (°C)") +
  theme_minimal() +
  labs(title = "Mean Temperature in Changi (Jan 2024)",
       caption = "Data Source: Your Dataset") +
  theme(legend.position = "right")
```

## 2 Government Procurement Data (Trial)
